<?php
namespace Magic;

/**
 * Test class for TypeHint.
 * Generated by PHPUnit on 2011-12-06 at 13:40:03.
 */
class TypeHintTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        TypeHint::register();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        TypeHint::unregister();
    }

    /**
     * @test
     */
    function type_hint_int()
    {
        $func = function(int $int)
        {
            return true;
        };
        assertTrue($func(1));
        assertTrue($func(3));
        $this->assertException('InvalidArgumentException', function() use($func)
        {
            $func(1.0);
        });
        $this->assertException('InvalidArgumentException', function() use($func)
        {
            $func("3");
        });
    }

    /**
     * @test
     */
    function type_hint_string()
    {
        $func = function(string $int)
        {
            return true;
        };
        assertTrue($func("abc"));
        assertTrue($func("123"));
        $this->assertException('InvalidArgumentException', function() use($func)
        {
            $func(1.0);
        });
        $this->assertException('InvalidArgumentException', function() use($func)
        {
            $func(1);
        });
    }

    /**
     * @param string $exceptionClass
     * @param callback $function
     */
    function assertException($exceptionClass, $function)
    {
        try {
            $function();
        } catch (\Exception $exception) {
            assertInstanceOf($exceptionClass, $exception);
        }
    }

}
